# Generated by Django 2.2 on 2021-06-20 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('wrong1', models.CharField(max_length=255)),
                ('wrong2', models.CharField(max_length=255)),
                ('wrong3', models.CharField(max_length=255)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='appTrivia.Collection')),
            ],
        ),
    ]
