# Generated by Django 2.2 on 2021-06-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTrivia', '0004_auto_20210629_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
